import os
import jwt
from fastapi import Request, HTTPException, status
from fastapi.security import HTTPBearer
from dotenv import load_dotenv

load_dotenv()

# Shared secret key string matching Java Spring Boot service
JWT_SECRET = os.getenv(
    "JWT_SECRET", 
    "fcac35f0013bd448bd10a736ef73a6e125aa9d585aef1bc01a01b210c9ddefb2"
)

security = HTTPBearer()

async def verify_jwt_token(request: Request) -> dict:
    """
    Extracts and validates the JWT token generated by Java Spring Boot (HS256/HS512).
    Decodes symmetrically in RAM without database latency.
    """
    auth_header = request.headers.get("Authorization")
    if not auth_header or not auth_header.startswith("Bearer "):
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Missing or invalid authentication bearer token format."
        )
    
    token = auth_header.split(" ")[1]
    
    try:
        # Allow both HS256 and HS512 to prevent algorithm mismatch rejections
        payload = jwt.decode(
            token, 
            JWT_SECRET.encode('utf-8'), 
            algorithms=["HS256", "HS512"]
        )
        return payload
        
    except jwt.ExpiredSignatureError:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Token has expired. Please log in again via Java Auth Service."
        )
    except jwt.InvalidTokenError as e:
        # This will print the precise cryptographic error to your Python terminal console
        print(f"❌ [JWT SECURITY ERROR] Failed to validate token signature: {str(e)}")
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail=f"Could not validate credentials: {str(e)}"
        )